name: React Demo Docker Image CI
run-name: React Demo Docker Image CI to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  push:
    branches: [ "master" ]
  #  pull_request:
    #  branches: [ "master" ]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build Docker image to personal Docker images registry
      run: docker build --file Dockerfile.dev --tag borisfon/docker-react .

    - name: Unit testing using fresh Docker image on GitHub
      run: docker run -e CI=true borisfon/docker-react npm run test

  deploy:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build Production Docker image to Google account container registry
      run: docker build . --file Dockerfile --tag gcr.io/dockerdeploymentdemo/small-20240810-035310:0.1.0

    - name: Push image to Google repo
      run: docker image push grc.io/dockerdeploymentdemo/small-20240810-035310:0.1.0

      #    - name: Package code for deployment
      #run: zip -r deploy.zip . -x '*.git*'

      #    - name: Deploy to AWS Elastic Beanstalk instance
        #uses: einaregilsson/beanstalk-deploy@v22
        #with:
        #aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        #aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        #application_name: frontend
        #environment_name: Frontend-env
        #region: us-east-2
        #version_label: Sample
        #deployment_package: deploy.zip
