name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: docker build --file Dockerfile.dev --tag borisfon/docker-react .
    - run: docker run -e CI=true borisfon/docker-react npm run test
